ktor:
    application:
        modules:
            - com.haykor.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  secret: ${JWT_SECRET:-super-secret-development-key-123}
  issuer: "http://0.0.0.0:8080"
  audience: "http://0.0.0.0:8080"
  realm: "Access to protected routes"
